# train/accelerate_configs/accelerate_config_cpu.yaml
compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: 'no' # CPU不支持bf16/fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: true # 关键设置