compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  deepspeed_config_file: ./train/zero_configs/zero3.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
machine_rank: 0
main_training_function: main
num_machines: 4
num_processes: 8
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: true
